<?xml version="1.0" encoding="utf-8"?><Database Name="data" Class="dataLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-DKETPGE\WTDATABASE;Initial Catalog=data;User ID=wtGuy;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="WT_DataManager.Properties.Settings" SettingsPropertyName="dataConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.usersRelTable" Member="usersRelTables">
    <Type Name="usersRelTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user1ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user2ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="since" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="received" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.usersTable" Member="usersTables">
    <Type Name="usersTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PassHash" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Userpic" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Online" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.usersTestRelTable" Member="usersTestRelTables">
    <Type Name="usersTestRelTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user1ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user2ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="since" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="received" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.usersTestTable" Member="usersTestTables">
    <Type Name="usersTestTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PassHash" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Userpic" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Online" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>